link:
  home: "https://www.railstutorial.org"
  help: "https://www.railstutorial.org/help"
  book: "https://www.railstutorial.org/book"
  contact: "https://www.railstutorial.org/contact"
  learn_enough: "https://www.learnenough.com/"
  screencasts: "https://screencasts.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
  author: "https://github.com/quangdvn-sun"
  news: "https://news.railstutorial.org/"

