link:
  home: "https://www.railstutorial.org"
  help: "https://www.railstutorial.org/help"
  book: "https://www.railstutorial.org/book"
  contact: "https://www.railstutorial.org/contact"
  learn_enough: "https://www.learnenough.com/"
  screencasts: "https://screencasts.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
  author: "https://github.com/quangdvn-sun"
  news: "https://news.railstutorial.org/"
validations:
  user:
    email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
    name_minlength: 5
    name_maxlength: 50
    email_minlength: 5
    email_maxlength: 255
    password_minlength: 6
    password_maxlength: 15
    avatar_default_size: 80
    avatar_size: 50
form:
  checkbox: "1"
pagination:
  per_page: 10
gravatar:
  link: "https://gravatar.com/emails"
time:
  expired: 2
